### ISSUE TITLE
Standardize Headers

### ISSUE THREAD

**Issue by cticenhour** [shannon-lab/zapdos#30]
I was reminded today that there are quite a few MOOSE headers that have snuck into the source code over the years that shouldn't be there. Thought I should make an issue as a reminder to remove those. 

Alternatively, we could make our own standard header as a replacement. Thoughts? @lindsayad @csdechant

**Comment by lindsayad** [comment]
I like the idea of having our own!

**Comment by cticenhour** [comment]
I do too! Maybe something very similar to the current in MOOSE, like:
```
//* This file is part of Zapdos,
//* an open-source application for the simulation of
//* low temperature plasmas
//*
//* Zapdos is powered by the MOOSE Framework
//* https://www.mooseframework.org
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

**Comment by csdechant** [comment]
This header looks good to me.

**Comment by lindsayad** [comment]
Looks pretty good to me too...although I might just say "plasmas" instead
of "low temperature plasmas". I would like it if someday we were able to do
high-temperature plasma simulation with zapdos too, whether that capability
comes from zapdos or zapdos submodules.

**Comment by keniley1** [comment]
This made me realize that I also have the same issue with CRANE...thanks for the heads up.

**Comment by cticenhour** [comment]
@keniley1  If you want to grab the python script I used to do this updating, you can get it from the `scripts` directory in my `new-headers` branch in #31. You should run it from the `crane` directory.

**Comment by cticenhour** [comment]
It makes it sooo much faster to do this :-)

**Comment by keniley1** [comment]
@cticenhour Awesome, thank you! I was just starting to think about how to write that kind of script myself.

**Comment by cticenhour** [comment]
You're welcome! I can't take credit for authoring it though - it's a modified MOOSE script. :-)
