### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by lindsayad** [shannon-lab/zapdos#70]
We've done a significant shuffling of input files recently, and as a result our `README` directions are pretty out-of-date. [This user](https://groups.google.com/d/msgid/zapdos-users/92c00507-f836-459b-952b-b0974d2794cfn%40googlegroups.com?utm_medium=email&utm_source=footer) (while having other issues) would run into problems trying to follow the `README`.

**Comment by cticenhour** [comment]
I can do that, unless you already started - I meant to do it the other day after my last PR and it slipped my mind.

**Comment by lindsayad** [comment]
I have not started. Go right ahead; much appreciated!
