### ISSUE TITLE
Updating and Adding Syntax Checks for "Problems" Input Files

### ISSUE THREAD

**Issue by csdechant** [shannon-lab/zapdos#72]
As previously discussed from a recent PR (https://github.com/shannon-lab/zapdos/pull/68) and forum post (https://groups.google.com/g/zapdos-users/c/drMKqU1xQqI/m/3YveOuhnAgAJ), the "Problems" directory need to be update with the latest syntax and have a Syntax Checks for these files.

**Comment by cticenhour** [comment]
Oh jeez, I completely forgot to go back and do this. 😅 Knew it would bite me if I hadn't done it immediately. Are all of these inputs exact duplicates of ones in the tests already? If so, we can just get rid of them rather than taking time to update them.

**Comment by cticenhour** [comment]
I left them in place, intending to ask you this same question.

**Comment by csdechant** [comment]
So, the input files "Lymberopoulos_with_argon_metastables.i" and "Lymberopoulos_with_argon_metastables_2D*" should be the same input files in "tests/Conference_Syntax_Tests/". The ones labelled "RF_Plasma*" should be the same as the Lymberopoulos files, but the RF_Plasma files uses Actions. The idea behind have the multiple input files for the same simulation was to show new users how they can use Zapdos either as a somewhat "Plug and Play" code with Actions or how it can be more customizable with just using Kernels. 

For the acceleration files, no, those files are not the same as the tests files (the test files solve a smaller and shorter version of these files), but I need to finish updating some changes to the acceleration methods.

For "ad_argon_chemistry.i", I don't think so. That file looks like an argon plasma and water interaction simulation, while the test in "automatic_differentiation/" is only an argon discharge.

**Comment by cticenhour** [comment]
Closing as the `problems` directory was removed in #132
